AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Lint/HandleExceptions:
  Enabled: false



Metrics/BlockLength:
  Exclude:
    - config/initializers/*
    - config/routes.rb
    - config/environments/*

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Style/BlockLength:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
